// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api_ecommerce;

#nullable disable

namespace api_ecommerce.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20231207175724_InitialCreation")]
    partial class InitialCreation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("api_ecommerce.Models.tb_productos", b =>
                {
                    b.Property<int>("it_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("it_id"), 1L, 1);

                    b.Property<string>("it_descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("it_detalle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("it_estado")
                        .HasColumnType("bit");

                    b.Property<string>("it_imagen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("it_precio")
                        .HasColumnType("float");

                    b.HasKey("it_id");

                    b.ToTable("tb_productos", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
